import streamlit as st
import pandas as pd
import plotly.express as px
import joblib
import numpy as np
import sklearn

# for reasons unknown to me, this prevents scrolling up
st.markdown(
    "<span style='color:white;'>_</span>",
    unsafe_allow_html=True
)

@st.cache_data
def load_model():
    return joblib.load("vo2_predict.joblib")

@st.cache_data
def load_stats():
    return pd.read_csv(st.secrets["small_stats_url"])

def predict(gene_dict):
    loaded_model = load_model()
    df = pd.DataFrame([gene_dict], index=[0])
    return (loaded_model.predict(df))[-1]


def render_result(col2, gene_dict):
    value = predict(gene_dict)
    st.session_state.vo2_value = value

    with col2:
        st.markdown(
            f"""
                    <div style="margin-top: 130px; font-size:18px; font-weight:bold; color:black; padding:10px; border-radius:8px;">
                        Predicted VO2Peak change (ml/kg/min) after 12 weeks of training: 
                    <span style="font-size:24px; font-weight:bold; color:blue;">
                        {value:+.2f} ml/kg/min
                    </span>
                    </div>
                    """,
            unsafe_allow_html=True
        )

def generate_random(mean, std, min_val, max_val):
    val = round(np.random.normal(mean, std),2)
    return str(np.clip(val, min_val, max_val))

def generate_figure(df_melted, display = True):
    fig = px.scatter(
        df_melted,
        x="Person",
        y="VO2Peak change (ml/kg/min)",
        color="Type",
        color_discrete_map={"Predicted": "red", "Ground Truth": "blue"},
        symbol="Type",
        symbol_map={"Predicted": "square", "Ground Truth": "circle"}
    )

    fig.update_layout(
        xaxis=dict(
            title="",
            showticklabels=False
        ),
        yaxis_title_font=dict(size=16),
        legend_title="",
        legend=dict(
            font=dict(size=15,
                color='black',
                family="Source Sans"
            )
        ),
        margin=dict(l=20, r=20, t=30, b=20),
        height=600,
        annotations=[
            dict(
                x=1,  # far right
                y=0,  # bottom
                xref="paper",
                yref="paper",
                text="R² = 0.526",
                showarrow=False,
                font=dict(
                    family="Source Sans",
                    size=20,
                    color="black"
                ),
                align="center",
                xanchor="right",
                yanchor="bottom",
                bordercolor="black",
                borderwidth=1,
                borderpad=4,
                bgcolor="rgba(217,217,214,0.8)",  # semi-transparent white
                opacity=0.9
            )
        ],
    )

    fig.update_traces(marker=dict(size=10))


    if "vo2_value" in st.session_state and not display:
        fig.add_scatter(
            x=[f"Your Prediction"],
            y=[round(st.session_state.vo2_value,2)],
            mode="markers",
            marker=dict(
                size=20,
                color="green",
                symbol="star"
            ),
            name="Your Prediction"
        )
    return fig



st.set_page_config(layout="wide")

predict_vals = [
    0.33, 0.51, 0.98, 5.15, -0.44,
    -1.77, 2.19, 2.28, 4.89, 4.01,
    -0.25, 6.12, 4.50, 9.12, 6.83,
    6.92, 10.74
]

target_vals = [
    -1.5, -1, -0.9, -0.5, 1.5,
    1.6, 1.8, 1.8, 2, 3.3,
    6.5, 6.7, 7.7, 7.8, 8,
    9.4, 12.3
]

genes = ["ADK","CD248","CD68","CHAD","CLIP3","CNIH3","COL6A1","CPO","CRAMP1","DNAJC25-GNG10","ECM1","ENSG00000253671","ENSG00000279662","ENSG00000279838","ENSG00000283228","ENSG00000287627","HOXB-AS1","IFFO1","LINC01996","MAGEF1","MOCOS","MPDZ","NCF4","P2RX5-TAX1BP3","RNF139-DT","SEC11C","SRRM4","STRBP","TMEM202-AS1","TTC7A","ZBTB39","ZSCAN26"]

df = pd.DataFrame({
    "Person": [f"Person {i+1}" for i in range(len(predict_vals))],
    "Predicted": predict_vals,
    "Ground Truth": target_vals
})

df_melted = df.melt(
    id_vars="Person",
    value_vars=["Predicted", "Ground Truth"],
    var_name="Type",
    value_name="VO2Peak change (ml/kg/min)"
)

empty = st.empty()

fig = generate_figure(df_melted=df_melted)
with empty:
    st.plotly_chart(fig, use_container_width=True)
col1, col2 = st.columns([2, 1])

with col1:
    st.markdown(
        f"""
        <div style="margin-top:0px; font-size:18px; color:black;">
            <p>Insert normalized basal expression of each gene:</p>
            <span style="font-size:15px; color:grey;">
                Normalized counts were generated by the DESeq2 pipeline using <br>the estimateSizeFactors() and counts(normalized = TRUE).
            </span>
        </div>
        """,
        unsafe_allow_html=True
    )
    st.markdown(
        """
        <style>
        /* Target the scroll-box container specifically */
        div[data-testid="stForm"] > div:nth-child(1) {
            height: 300px;      /* match plot height */
            overflow-y: auto;   /* enable vertical scroll */
        }
        </style>
        """,
        unsafe_allow_html=True
    )

    with st.form("gene_input_form", clear_on_submit=False):
        # All text inputs go here
        gene_inputs = {}
        if "gen_random" not in st.session_state:
            st.session_state.gen_random = False

        if "random_gene_vals" not in st.session_state:
            st.session_state.random_gene_vals = {}  # store randoms here

        df = load_stats()
        df = df.set_index("Unnamed: 0")

        for g in genes:
            if st.session_state.gen_random:
                if g not in st.session_state.random_gene_vals:
                    # Generate only once per gene
                    row_df = df.loc[g]
                    st.session_state.random_gene_vals[g] = generate_random(
                        row_df["mean"], row_df["std"], row_df["min"], row_df["max"]
                    )
                gene_inputs[g] = st.text_input(g, value=st.session_state.random_gene_vals[g])

            else:
                gene_inputs[g] = st.text_input(g, value="")

        form1, form2, form3 = st.columns([1,1,1])

        with form1:
            submitted = st.form_submit_button("Submit")
        with form2:
            generate_syn = st.form_submit_button("Generate Values")
        with form3:
            remove_syn = st.form_submit_button("Remove Values")

        if submitted:
            if any(v.strip() == "" for v in gene_inputs.values()):
                st.error("Please fill in all gene values.")
            else:
                st.success("Values successfully submitted!")
                gene_dict_float = {k: float(v) for k, v in gene_inputs.items()}
                render_result(col2, gene_dict_float)
        if generate_syn:
            st.session_state.gen_random = True
            st.session_state.random_gene_vals = {}
            if "vo2_value" in st.session_state:
                st.session_state.pop("vo2_value")
            st.rerun()

        if remove_syn:
            st.session_state.gen_random = False
            st.session_state.random_gene_vals = {}
            if "vo2_value" in st.session_state:
                st.session_state.pop("vo2_value")
            st.rerun()


if "vo2_value" in st.session_state:
    new_fig = generate_figure(df_melted, display = False)
    with empty:
        st.plotly_chart(new_fig, use_container_width=True)
